# Problem Set 1
Answer for Group A2

# Problem 1: Tensors and Automatic Differentiation

PyTorch tensors are similar to NumPy arrays but can run on GPUs and
support automatic differentiation. In this problem, you will explore
tensor operations and PyTorch’s autograd system.

In [1]:
# install packages
import torch

In [6]:
# torch set up
torch.manual_seed(42)

if torch.backends.mps.is_available():
    DEVICE = torch.device("mps") # Apple Silicon Metal Performance Shaders
elif torch.cuda.is_available():
    DEVICE = torch.device("cuda") # GPU
else:
    DEVICE = torch.device("cpu")

**(1a)** Create the following tensors and perform the specified
operations:

1.  Create a tensor `a` containing the values \[1.0, 2.0, 3.0, 4.0,
    5.0\]

In [34]:
# 1.a.1
VALUES = [1.0, 2.0, 3.0, 4.0, 5.0]
a = torch.tensor(VALUES, dtype=torch.float32).to(DEVICE)
print(f'a: {a}')

a: tensor([1., 2., 3., 4., 5.])


2.  Create a 3×3 tensor `B` filled with ones

In [40]:
# 1.a.2
SHAPE = (3,3)
B = torch.ones(SHAPE)
print(f'B: {B}')

B: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


3.  Reshape `a` to a 5×1 column vector

In [37]:
# 1.a.3
a_transposed = a.reshape(-1,1)
print(f'a transposed to a 5x1 column vector: \n {a_transposed}')

a transposed to a 5x1 column vector: 
 tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.]])


4.  Compute the element-wise square of `a`

In [42]:
# 1.a.4
a_squared = a * a
print(f'a squared element-wise: \n {a_squared}')

a squared element-wise: 
 tensor([ 1.,  4.,  9., 16., 25.])


5.  Compute the matrix product of `B` with itself

In [41]:
# 1.a.5
B_squared = B @ B
print(f'B squared (matrix product): \n {B_squared}')

B squared (matrix product): 
 tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])


**(1b)** PyTorch’s automatic differentiation (autograd) computes
gradients automatically. Consider the function $f(x) = x^2 + 3x + 1$.

1.  Compute $\frac{df}{dx}$ analytically. What is its value at $x = 2$?

$\frac{df}{dx} = 2x + 3$

At $x = 2$, $\frac{df}{dx} = 2(2) + 3 = 7$

2.  Create a tensor `x = torch.tensor([2.0], requires_grad=True)` and
    compute `y = x**2 + 3*x + 1`

In [49]:
# 1.b.2
x = torch.tensor([2.0], requires_grad=True)
y = x**2 + 3*x + 1
y

tensor([11.], grad_fn=<AddBackward0>)

3.  Call `y.backward()` to compute the gradient, then print `x.grad`

In [50]:
# 1.b.3
y.backward()
print(x.grad)

tensor([7.])


4.  Verify that PyTorch’s gradient matches your analytical result

In [52]:
print(x.grad.dim())

1


PyTorch calculated a gradient for the function at $x = 2$ as a scalar with value 7. This matches my analytical result.

**(1c)** Consider the function $g(x, y) = x^2 y + y^3$.

1.  Compute $\frac{\partial g}{\partial x}$ and
    $\frac{\partial g}{\partial y}$ analytically

$\frac{\partial g}{\partial x} = 2xy$

$\frac{\partial g}{\partial y} = x^2 + 3y^2$

2.  Use PyTorch to compute both partial derivatives at $(x, y) = (1, 2)$

In [ ]:
# 1.c.2
x1 = torch.tensor([1.0], requires_grad=True)
y1 = torch.tensor([2.0], requires_grad=True)
g = (x^2)*y + y^3
g.backward()
print(x1.grad)
print(y1.grad)

NotImplementedError: "bitwise_xor_cpu" not implemented for 'Float'

3.  Verify the results match

# Problem 2: Linear Regression in PyTorch

In this problem, you will implement linear regression using PyTorch’s
neural network modules and optimizers.

In [56]:
# Generate synthetic data for linear regression
n_samples = 100
true_weight = 3.5
true_bias = 1.2

X = torch.randn(n_samples, 1)
y = true_weight * X + true_bias + 0.3 * torch.randn(n_samples, 1)